// <auto-generated />
namespace MediaPlayer.Data.Migrations.ApplicationIdentityDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CustomFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CustomFile));
        
        string IMigrationMetadata.Id
        {
            get { return "201610230634396_CustomFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
